### ISSUE TITLE
Is there an external parameter, the transformation matrix from odmo coordinate system to camera coordinate system, in the market dataset？

### ISSUE THREAD

**Issue by ChenHuang20** [lifelong-robotic-vision/openloris-scene-tools#1]
or the transformation matrix from odmo coordinate system to any other coordinate system, in the market dataset

Thanks!

**Comment by cedrusx** [comment]
Then transformations are stored in [openloris_tf_data.py](https://github.com/lifelong-robotic-vision/openloris-scene-tools/blob/master/benchmark/openloris_tf_data.py).

> is the odomer's coordinate system is the base_link?

Yes.
