### ISSUE TITLE
Is there an intrinsic parameters of T265 and D435i camera for calibration.

### ISSUE THREAD

**Issue by shanpenghui** [lifelong-robotic-vision/openloris-scene-tools#2]
I can't find the intrinsic parameters file of cameras inproject. Is there provided?

**Comment by cedrusx** [comment]
The intrinsics are with the data. In ROS bags they are on camera_info/imu_info topics. In the packages they are in yaml files.

**Comment by shanpenghui** [comment]
@cedrusx Tks for replying.
